/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package EmailReader.GUI;

import EmailReader.AccountData;
import EmailReader.Protocol;

/**
 *
 * @author Roman Nort
 */
public class AccountDataDialog extends javax.swing.JDialog {

    
    /**
     * Contains data fields for existing account
     */
    private AccountData accountData;
    
    private boolean result = true;
    
    /** Edits existed account
     * 
     * @param accountData Existed account data object
     * @param parent Parent window for this dialog
     * @param modal Determines is window modal or not
     */
    public AccountDataDialog(AccountData accountData, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.accountData = accountData;
        PopulateFields();
    }
    
    public boolean GetResult()
    {
        return result;
    }
    
    /**
     * Default c-tor.
     */
    public AccountDataDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.accountData = new AccountData();
        PopulateFields();
    }
    

    private void PopulateFields()
    {
        this.tbServerLogin.setText(accountData.Login);
        this.tpPassword.setText(accountData.Password);
        this.tpPasswordConfirmation.setText(accountData.PasswordConfirmation);
        this.tbSmtpHost.setText(accountData.HostOut.Host);
        this.tbSmtpPort.setText(accountData.HostOut.Port);
        this.cbSmtpSsl.setEnabled(accountData.HostOut.Ssl);
        
        if (accountData.HostIn.Protocl.equals(Protocol.NONE)){
            Boolean isImap = false;
            if (accountData.HostIn.Protocl.equals(Protocol.IMAP) ||
                accountData.HostIn.Protocl.equals(Protocol.IMAPS)){
                isImap  = true;
            }
            this.rbImap.setEnabled(isImap);
            this.rbPop3.setEnabled(!isImap);
            if (isImap){
                this.tbImapHost.setText(accountData.HostIn.Host);
                this.tbImapPort.setText(accountData.HostIn.Port);
                this.cbImapSsl.setEnabled(accountData.HostIn.Ssl);
            }else{
                this.tbPop3Host.setText(accountData.HostIn.Host);
                this.tbPop3Port.setText(accountData.HostIn.Port);
                this.cbPop3Ssl.setEnabled(accountData.HostIn.Ssl);
            }
        }        
    }
    
    /**
     * Saves user changes to accountData field.
     */
    private void SaveChanges()
    {
        accountData.Login = this.tbServerLogin.getText();
        accountData.Password = this.tpPassword.getPassword().toString();
        accountData.PasswordConfirmation = this.tpPasswordConfirmation.getPassword().toString();
        accountData.HostOut.Host = this.tbSmtpHost.getText();
        accountData.HostOut.Port = this.tbSmtpPort.getText();
        accountData.HostOut.Ssl = this.cbSmtpSsl.isEnabled();
        
        if (this.rbImap.isEnabled())
        {
            accountData.HostIn.Protocl = Protocol.IMAP;
            accountData.HostIn.Host = this.tbImapHost.getText();
            accountData.HostIn.Port = this.tbImapPort.getText();
            accountData.HostIn.Ssl = this.cbImapSsl.isEnabled();
        }
        else
        {
            accountData.HostIn.Protocl = Protocol.POP3;
            accountData.HostIn.Host = this.tbPop3Host.getText();
            accountData.HostIn.Port = this.tbPop3Port.getText();
            accountData.HostIn.Ssl = this.cbPop3Ssl.isEnabled();
        }
    }
    
    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        grpInProtocol = new javax.swing.ButtonGroup();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        tbServerLogin = new javax.swing.JTextField();
        lblServerLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tbSmtpPort = new javax.swing.JTextField();
        cbSmtpSsl = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        tpPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        tpPasswordConfirmation = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        tbSmtpHost = new javax.swing.JTextField();
        tbPop3Host = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tbPop3Port = new javax.swing.JTextField();
        cbPop3Ssl = new javax.swing.JCheckBox();
        tbImapHost = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tbImapPort = new javax.swing.JTextField();
        cbImapSsl = new javax.swing.JCheckBox();
        rbPop3 = new javax.swing.JRadioButton();
        rbImap = new javax.swing.JRadioButton();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblServerLogin.setText("Server Login");

        jLabel1.setText("Port");

        tbSmtpPort.setText("10");

        cbSmtpSsl.setText("SSL");

        jLabel2.setText("Password");

        jLabel3.setText("Confirmation");

        jLabel4.setText("SMTP Server");

        jLabel6.setText("Port");

        tbPop3Port.setText("10");

        cbPop3Ssl.setText("SSL");

        jLabel8.setText("Port");

        tbImapPort.setText("10");

        cbImapSsl.setText("SSL");

        grpInProtocol.add(rbPop3);
        rbPop3.setText("POP3");

        grpInProtocol.add(rbImap);
        rbImap.setText("IMAP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbImap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbImapHost, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbImapPort, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbImapSsl))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(tpPasswordConfirmation, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblServerLogin)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tbServerLogin)
                                            .addComponent(tpPassword))))
                                .addGap(14, 14, 14))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(tbSmtpHost)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbSmtpPort, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSmtpSsl))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbPop3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbPop3Host, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbPop3Port, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPop3Ssl)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbServerLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServerLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tpPasswordConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tbSmtpHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(tbSmtpPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSmtpSsl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbPop3Host, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tbPop3Port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPop3Ssl)
                    .addComponent(rbPop3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbImapHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(tbImapPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbImapSsl)
                    .addComponent(rbImap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        SaveChanges();
        this.dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        result = false;
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountDataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountDataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountDataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountDataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AccountDataDialog dialog = new AccountDataDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JCheckBox cbImapSsl;
    private javax.swing.JCheckBox cbPop3Ssl;
    private javax.swing.JCheckBox cbSmtpSsl;
    private javax.swing.ButtonGroup grpInProtocol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblServerLogin;
    private javax.swing.JRadioButton rbImap;
    private javax.swing.JRadioButton rbPop3;
    private javax.swing.JTextField tbImapHost;
    private javax.swing.JTextField tbImapPort;
    private javax.swing.JTextField tbPop3Host;
    private javax.swing.JTextField tbPop3Port;
    private javax.swing.JTextField tbServerLogin;
    private javax.swing.JTextField tbSmtpHost;
    private javax.swing.JTextField tbSmtpPort;
    private javax.swing.JPasswordField tpPassword;
    private javax.swing.JPasswordField tpPasswordConfirmation;
    // End of variables declaration//GEN-END:variables
}
